#! /bin/sh

xrandr -s 1920x1080
setxkbmap es
xsetroot -cursor_name left_ptr

#pgrep -x redshift > /dev/null || redshift -c ~/.config/redshift/redshift.conf &

$HOME/.config/polybar/launch.sh && $HOME/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "L" "I" "N" "U" "X"

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# ---

bspc config focused_border_color '#8bcc6a'
bspc config normal_border_color '#999999'
