[global/wm]
margin-bottom = 0
margin-top = 0
include-file = ~/.config/polybar/colors.ini

[bar/main]
wm-restack = bspwm
locale = es_ES.UTF-8
offset-y = 10
bottom = false
border-size = 2pt
border-color = ${color.fg}
line-size = 2
line-color = ${color.fg}
fixed-center = true
height = 50px
background = ${color.bg}
foreground = ${color.fg}
padding = 3
separator = |
font-0 = MononokiNerdFont:size=14;2
font-1 = MononokiNerdFont:size=20;4
module-margin = 1 

[bar/logo]
inherit = bar/main
offset-x = 10
width = 50px
padding = 0
modules-center = logo

[bar/fecha]
inherit = bar/main
offset-x = 70px
width = 200px
modules-center = date

[bar/red]
inherit = bar/main
width = 200px
offset-x = 280px
modules-center = network

[bar/vpn_status]
inherit = bar/main
offset-x = 490px
width = 240px
modules-center = vpn_status

[bar/objetivo]
inherit = bar/main
offset-x = 1440px
width = 300px
modules-center = objetivo

[bar/bateria]
inherit = bar/main
offset-x = 1750px
width = 100px
modules-center = battery-label 

[bar/sistema]
inherit = bar/main
offset-x = 1860px
width = 50px
modules-center = sistema

[bar/escritorios]
inherit = bar/main
offset-x = 960px
width = 169px
padding = 0
modules-left = xworkspaces

# Modules

[module/logo]
type = custom/text
content = "  "
content-font = 2

[module/date]
type = internal/date
interval = 1
time = %H:%M
date = %b %d
label = %date% | %time%

[module/network]
type = internal/network
interface-type = wired
interval = 1
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = %{A1:hostname -I | awk '{print $1}' | tr -d "\n" | xclip -sel clip:}󰈀  %{F#fff}%local_ip%%{F-}%{A}
format-disconnected-foreground = #AAA
label-disconnected = disconnected

[module/vpn_status]
type = custom/script
interval = 1
exec = ~/.config/bin/vpn_status.sh

[module/objetivo]
type = custom/script
interval = 1
exec = ~/.config/bin/objetivo.sh

[module/battery-label]
type = internal/battery
battery = BAT0
full-at = 100
low-at = 25
format-charging = <label-charging>
label-charging = %percentage%% 󰂄
format-discharging = <label-discharging> <ramp-capacity>
label-discharging = %{F#fff}%percentage%%%{F-}
format-low = <label-low> <ramp-capacity>
label-low = %{F#ff0000}%percentage%%
label-full = %percentage%%
ramp-capacity-0 = 󰂎
ramp-capacity-1 = 󰁺
ramp-capacity-2 = 󰁻
ramp-capacity-3 = 󰁼
ramp-capacity-4 = 󰁽
ramp-capacity-5 = 󰁾
ramp-capacity-6 = 󰁿
ramp-capacity-7 = 󰂀
ramp-capacity-8 = 󰂁
ramp-capacity-9 = 󰂂
ramp-capacity-10 = 󰁹

[module/battery-ramp]
type = internal/battery
battery = BAT0
full-at = 100
low-at = 20
format-charging = <ramp-capacity>
format-discharging = <ramp-capacity>

[module/sistema]
type = custom/text
content = X

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = #373B41 
label-active-padding = 1
label-active-underline = ${color.fg}

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = #aaa
label-empty-padding = 1

